### ISSUE TITLE
Create a function to request permission tables from Supabase

### ISSUE THREAD

**Issue by Gallost** [jixsu/protoshell#11]
The function should request and retrieve a table from Supabase. This requires Supabase to have an endpoint setup for the Laravel web app to hit.

Write a controller to request the permission table for a specified model from Supabase. Then, store the table into the corresponding local schema.

Bonus (could be another item): fire a job to process a new locked schema once the permission table is received from Supabase.

**Comment by adrian-salvador** [comment]
done !

**Comment by adrian-salvador** [comment]
Work done:
Addition of PermissionsManager Controller that retrieves a permission records that were changes in JSON format and updates the affected company permissions table records and triggers a job to process a new locked schema

See commit [6231804](https://github.com/Gallost/endpoint_server/commit/623180415ba5ebbc7b9739fa8c3c76def23883db)
