### ISSUE TITLE
[DEPRECATED] Change ProtoShell-related files to be securely accessible by select (root) user(s) and prefix file names

### ISSUE THREAD

**Issue by adrian-salvador** [jixsu/protoshell#23]
Sensitive files containing calls to functions requiring proto_key should have specific permissions setup such that only privileged users may view/edit. These files should be prefixed with an easily identifiable token to distinguish them from normal files.

**Comment by adrian-salvador** [comment]
WIP

**Comment by Gallost** [comment]
This feature is no longer required due to a change in ProtoShell design on company's end => ProtoShell is now running as an independent Laravel application which performs processing on raw and perms data.

**Comment by Gallost** [comment]
This feature is no longer required due to a change in ProtoShell design on company's end => ProtoShell is now running as an independent Laravel application which performs processing on raw and perms data.
