### ISSUE TITLE
Override methods in the ProtoShelled trait to secure (in)direct access to sensitive Models

### ISSUE THREAD

**Issue by adrian-salvador** [jixsu/protoshell#25]
**IMPORTANT: a "reverse" access can happen if someone establishes a relational connection by a foreign key from a direct-access-okay model to a sensitive model. This needs to be addressed**
```
$x = new Customers();
$x = $x->first(); // retrieves a customer 
$x = $x->hasOne(CustomersRaw::class, 'id', 'id'); // associates to a raw data entry by id 
$x->get(); // retrieves the raw data
```

In the best case scenario, we need to implement proto_key check for all methods for a model that may provide direct (or even indirect access) to sensitive information.

Methods Completed:
- query
- all
- with
- where
- find
- first
- firstorfail
- latest
- oldest

**Comment by adrian-salvador** [comment]
WIP

**Comment by Gallost** [comment]
This has been complete to a satisfactory degree given the current direction of the ProtoShell service design. No further development is needed at this point in time due to the unlikelihood of unauthorized access into ProtoShell service source code.
